#ifndef ATA_H
#define ATA_H

#define ATA_PRIMARY_BASEPORT 0x1F0
#define ATA_SECONDARY_BASEPORT 0x170

#define ATA_REG_PRIMARY_DEVCONTROL 0x3F6
#define ATA_REG_SECONDARY_DEVCONTROL 0x376

#define ATA_REG_DATA 0
#define ATA_REG_FEATURE 1
#define ATA_REG_ERRORINFO 1
#define ATA_REG_SECTORCOUNT 2
#define ATA_REG_LBALO 3
#define ATA_REG_LBAMID 4
#define ATA_REG_LBAHI 5
#define ATA_REG_DRIVE 6
#define ATA_REG_STATUSCMD 7

#define ATA_STATUS_ERR 0x01
#define ATA_STATUS_DRQ 0x08
#define ATA_STATUS_SRV 0x10
#define ATA_STATUS_DF  0x20
#define ATA_STATUS_RDY 0x40
#define ATA_STATUS_BSY 0x80


typedef enum
{
    ATACHANNEL_FIRST_MASTER,
    ATACHANNEL_FIRST_SLAVE,
    ATACHANNEL_SECOND_MASTER,
    ATACHANNEL_SECOND_SLAVE
} HDD_ATACHANNEL;


#endif
